### ISSUE TITLE
Publish to Firefox extension

### ISSUE THREAD

**Issue by madeindjs** [Guuri11/token-inspector#1]
I just try to load the extension on Firefox 124, and it works as is. Is there any plan to publish the extension on [Firefox Add-on](https://addons.mozilla.org/en-US/firefox/)?

**Comment by Guuri11** [comment]
I was not thinking about to do the extension for firefox, but give me some time to work on it. Thanks!

**Comment by Guuri11** [comment]
![Screenshot from 2024-04-21 10-47-42](https://github.com/Guuri11/token-inspector/assets/48799796/05ef2d51-9a2d-41d9-a2b0-67118651f339)

@madeindjs Hi there! I just want to let you know that I submitted the extension to be available in firefox also. Once is published I'll let you know!

**Comment by Guuri11** [comment]
@madeindjs https://addons.mozilla.org/es/firefox/addon/token-devtools-inspector/ here you have :D
